In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import matplotlib.pyplot as plt
% matplotlib inline
#准备CCSS数据集
ccss = pd.read_excel("ccss_sample.xlsx")
ccss.head()

time  id  s0 s2  s3     s4             s5  s7          s9 c0_1  \
0  200704   1  北京  男  20     本科     公司普通职员（白领）  未婚  2000-2999元    0   
1  200704   2  北京  男  24  高中/中专     公司普通职员（白领）  未婚  6000-7999元    0   
2  200704   3  上海  男  20  高中/中专  无业/待业/失业/家庭主妇  未婚  1000-1499元    0   
3  200704   4  北京  女  65     大专       企/事业管理人员  已婚  1000-1499元    0   
4  200704   5  上海  女  40  高中/中专     公司普通职员（白领）  已婚      99拒绝回答    0   

      ...         Qs9  Qa3  Qa4  Qa8  Qa9 Qa10  Qa16      index1     index1a  \
0     ...      2500.0  100  200  200  200  100   100  109.349371   88.035919   
1     ...      7000.0  100  100  100  150  200   100   93.728032   88.035919   
2     ...      1250.0  100  150  150  100  100   100   93.728032   88.035919   
3     ...      1250.0  150  150  100  100  100   200  109.349371  154.062858   
4     ...         NaN  100  100  100  100  150   100   85.917363   88.035919   

      index1b  
0  121.071238  
1   96.856991  
2   96.856991  
3   84.749867  
4   84.749867  

[5 rows x 32 columns]

In [2]:
#级联
nd = np.random.randint(0, 10, size = (3,3))
nd

array([[5, 3, 4],
       [3, 1, 1],
       [7, 6, 9]])

In [3]:
np.concatenate((nd,nd), axis = 0)

array([[5, 3, 4],
       [3, 1, 1],
       [7, 6, 9],
       [5, 3, 4],
       [3, 1, 1],
       [7, 6, 9]])

In [4]:
np.concatenate((nd,nd), axis = 1)

array([[5, 3, 4, 5, 3, 4],
       [3, 1, 1, 3, 1, 1],
       [7, 6, 9, 7, 6, 9]])

In [5]:
def make_df(cols, inds):
    data = {c:[c+str(i) for i in inds]for c in cols}
    return DataFrame(data, index = inds, columns = cols)

In [6]:
make_df(['A','B'],[1,2])

A   B
1  A1  B1
2  A2  B2

In [7]:
df1 = make_df(list('AB'),[0,1])
df2 = make_df(list('AB'),[2,3])
pd.concat([df1,df2])

A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [8]:
pd.concat([df1,df2],axis=1)

A    B    A    B
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2  NaN  NaN   A2   B2
3  NaN  NaN   A3   B3

In [9]:
df3 = make_df(list('AB'),[0,1,2])
df4 = make_df(list('AB'),[1,2,3])

In [10]:
df5 = pd.concat((df3, df4))
df5

A   B
0  A0  B0
1  A1  B1
2  A2  B2
1  A1  B1
2  A2  B2
3  A3  B3

In [11]:
df5.loc[[1,2]]

A   B
1  A1  B1
1  A1  B1
2  A2  B2
2  A2  B2

In [12]:
df  = DataFrame(np.random.randint(0,10,size = (2,2)),
                columns = ['张三','张三'], index = ['A','B'])
df

张三  张三
A   0   9
B   0   9

In [13]:
x = make_df(list('XY'),['a','b'])
y = make_df(list('XY'),['A','B'])
#keys可以使合并的数据更加清晰
pd.concat([x,y],keys = ['x','y'])

X   Y
x a  Xa  Ya
  b  Xb  Yb
y A  XA  YA
  B  XB  YB

In [14]:
df1 = make_df(list('AB'),[1,3])
df2 = make_df(list('BC'),[2,4])

In [15]:
pd.concat([df1,df2],join='inner')

B
1  B1
3  B3
2  B2
4  B4

In [16]:
df3 = make_df(list('ACD'),[0,1,2])
df4 = make_df(list('CDF'),[3,4,5])

In [17]:
# join_axes以某一个DataFrame列索引为新的索引值
pd.concat([df3,df4],join_axes=[df3.columns])

A   C   D
0   A0  C0  D0
1   A1  C1  D1
2   A2  C2  D2
3  NaN  C3  D3
4  NaN  C4  D4
5  NaN  C5  D5

In [18]:
df1 = make_df(['大众','福克斯'],[0,1,2,3,4])
df2 = make_df(['大众','福克斯'],[5,6,7,8,9])

In [19]:
#append更加灵活和方便
df1.append(df2)

大众   福克斯
0  大众0  福克斯0
1  大众1  福克斯1
2  大众2  福克斯2
3  大众3  福克斯3
4  大众4  福克斯4
5  大众5  福克斯5
6  大众6  福克斯6
7  大众7  福克斯7
8  大众8  福克斯8
9  大众9  福克斯9

In [22]:
# merge合并
df1 = DataFrame({'employee': ['Po','Sara','Danis'],
                 'group': ['sail','counting','marketing']})
df2 = DataFrame({'employee': ['Po','Sara','Bush'],
                 'work_time': [2,3,1]})
display(df1, df2)

employee      group
0       Po       sail
1     Sara   counting
2    Danis  marketing

employee  work_time
0       Po          2
1     Sara          3
2     Bush          1

In [23]:
#一对一合并
pd.merge(df1, df2)

employee     group  work_time
0       Po      sail          2
1     Sara  counting          3

In [24]:
pd.concat([df1, df2])

employee      group  work_time
0       Po       sail        NaN
1     Sara   counting        NaN
2    Danis  marketing        NaN
0       Po        NaN        2.0
1     Sara        NaN        3.0
2     Bush        NaN        1.0

In [25]:
pd.concat([df1,df2], axis = 1)

employee      group employee  work_time
0       Po       sail       Po          2
1     Sara   counting     Sara          3
2    Danis  marketing     Bush          1

In [27]:
df1 = DataFrame({'employee': ['Po','Sara','Danis'],
                 'group': ['sail','counting','marketing']})
df2 = DataFrame({'employee': ['Po','Po','Bush'],
                 'work_time': [2,3,1]})
display(df1, df2)

employee      group
0       Po       sail
1     Sara   counting
2    Danis  marketing

employee  work_time
0       Po          2
1       Po          3
2     Bush          1

In [28]:
# 多对一合并
pd.merge(df1,df2)

employee group  work_time
0       Po  sail          2
1       Po  sail          3

In [29]:
df1 = DataFrame({'employee': ['Po','Po','Danis'],
                 'group': ['sail','counting','marketing']})
df2 = DataFrame({'employee': ['Po','Po','Bush'],
                 'work_time': [2,3,1]})
display(df1, df2)

employee      group
0       Po       sail
1       Po   counting
2    Danis  marketing

employee  work_time
0       Po          2
1       Po          3
2     Bush          1

In [31]:
# 在进行多对多合并时，每一个数据都没有放过
pd.merge(df1, df2)

employee     group  work_time
0       Po      sail          2
1       Po      sail          3
2       Po  counting          2
3       Po  counting          3

In [38]:
df3 = DataFrame({'employee': ['Po','Summer','Flower'],
                 'group': ['sail','marketing','serch'],
                 'salary': [12000, 10000, 8000]})
df4 = DataFrame({'employee': ['Po','Winter','Flower'],
                 'group': ['marketing','marketing','serch'],
                 'work_time': [2, 1, 5]})
display(df3, df4)

employee      group  salary
0       Po       sail   12000
1   Summer  marketing   10000
2   Flower      serch    8000

employee      group  work_time
0       Po  marketing          2
1   Winter  marketing          1
2   Flower      serch          5

In [39]:
pd.merge(df3, df4)

employee  group  salary  work_time
0   Flower  serch    8000          5

In [40]:
pd.merge(df3,df4,on = 'employee')

employee group_x  salary    group_y  work_time
0       Po    sail   12000  marketing          2
1   Flower   serch    8000      serch          5

In [43]:
pd.merge(df3,df4,on = 'group', suffixes=['_A','_B'])

employee_A      group  salary employee_B  work_time
0     Summer  marketing   10000         Po          2
1     Summer  marketing   10000     Winter          1
2     Flower      serch    8000     Flower          5

In [45]:
pd.merge(df3, df4, left_on = 'employee', right_on='employee')

employee group_x  salary    group_y  work_time
0       Po    sail   12000  marketing          2
1   Flower   serch    8000      serch          5

In [47]:
df3 = DataFrame({'employer': ['Po','Summer','Flower'],
                 'Team': ['sail','marketing','serch'],
                 'salary': [12000, 10000, 8000]})
df4 = DataFrame({'employee': ['Po','Winter','Flower'],
                 'group': ['marketing','marketing','serch'],
                 'work_time': [2, 1, 5]})
display(df3, df4)

Team employer  salary
0       sail       Po   12000
1  marketing   Summer   10000
2      serch   Flower    8000

employee      group  work_time
0       Po  marketing          2
1   Winter  marketing          1
2   Flower      serch          5

In [48]:
pd.merge(df3, df4, left_on = 'employer', right_on='employee')

Team employer  salary employee      group  work_time
0   sail       Po   12000       Po  marketing          2
1  serch   Flower    8000   Flower      serch          5

In [49]:
pd.merge(df3, df4, left_on = 'Team', right_on='group')

Team employer  salary employee      group  work_time
0  marketing   Summer   10000       Po  marketing          2
1  marketing   Summer   10000   Winter  marketing          1
2      serch   Flower    8000   Flower      serch          5

In [51]:
df1 = DataFrame({'age':[18,22,33],'height':[175,169,180]})
df2 = DataFrame({'age':[18,23,31],'weight':[65,70,80]})

In [52]:
pd.merge(df1,df2)

age  height  weight
0   18     175      65

In [53]:
pd.merge(df1, df2, how = 'outer')

age  height  weight
0   18   175.0    65.0
1   22   169.0     NaN
2   33   180.0     NaN
3   23     NaN    70.0
4   31     NaN    80.0

In [54]:
pd.merge(df1, df2, how = 'left')

age  height  weight
0   18     175    65.0
1   22     169     NaN
2   33     180     NaN

In [55]:
pd.merge(df1,df2, how = 'right')

age  height  weight
0   18   175.0      65
1   23     NaN      70
2   31     NaN      80

In [56]:
display(df3, df4)

Team employer  salary
0       sail       Po   12000
1  marketing   Summer   10000
2      serch   Flower    8000

employee      group  work_time
0       Po  marketing          2
1   Winter  marketing          1
2   Flower      serch          5

In [57]:
df3.columns = ['group', 'employee', 'salary']
display(df3, df4)

group employee  salary
0       sail       Po   12000
1  marketing   Summer   10000
2      serch   Flower    8000

employee      group  work_time
0       Po  marketing          2
1   Winter  marketing          1
2   Flower      serch          5

In [58]:
pd.merge(df3,df4, on = 'employee', suffixes=['_李','_王'])

group_李 employee  salary    group_王  work_time
0    sail       Po   12000  marketing          2
1   serch   Flower    8000      serch          5