In [1]:
import numpy as np
# fft 傅里叶转换， ifft傅里叶反转
from numpy.fft import fft, ifft
from PIL import Image

In [2]:
pic = Image.open('Photo6.jpg')

In [4]:
#pic.show()
pic

In [9]:
pic_data = np.fromstring(pic.tobytes(),dtype=np.int8)
# 有负数是因为int<128,颜色值为0-255
pic_data

array([33, 26, 33, ..., 52, 42, 50], dtype=int8)

In [10]:
pic_data_fft = fft(pic_data)
# 将真实数据转换成频域
pic_data_fft

array([  7013405.00000000       +0.j        ,
        16332705.61648151-27051314.73495049j,
         9842766.87711522 -9248219.89842544j, ...,
        -9503841.02126344 +8499848.16489301j,
         9842766.87711533 +9248219.89842534j,
        16332705.61648182+27051314.73495033j])

In [11]:
# 将傅里叶的数据去除低频的波，设置为0
np.where(np.abs(pic_data_fft)<1e5, 0, pic_data_fft)

array([  7013405.00000000       +0.j        ,
        16332705.61648151-27051314.73495049j,
         9842766.87711522 -9248219.89842544j, ...,
        -9503841.02126344 +8499848.16489301j,
         9842766.87711533 +9248219.89842534j,
        16332705.61648182+27051314.73495033j])

In [12]:
pic_data_fft[np.where(np.abs(pic_data_fft)<1e5)] = 0

In [13]:
pic_data_ifft = ifft(pic_data_fft)
pic_data_ifft

array([ 34.84987702 -1.96914024e-13j,  26.25666917 -1.30837760e-13j,
        36.15377779 -1.42636807e-13j, ...,  25.56808774 +4.70641500e-14j,
        18.00501800 -1.14524226e-14j,  25.73229892 -2.09361541e-14j])

In [16]:
pic_data_real = np.real(pic_data_ifft)
pic_data_real

array([ 34.84987702,  26.25666917,  36.15377779, ...,  25.56808774,
        18.005018  ,  25.73229892])

In [19]:
pic_data_result = np.int8(pic_data_real)
pic_data_result

array([34, 26, 36, ..., 25, 18, 25], dtype=int8)

In [21]:
pic_Image = Image.frombytes(size = pic.size, mode = pic.mode, data=pic_data_result)

In [22]:
pic_Image.show()