In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
from matplotlib import pyplot as plt 
% matplotlib inline

In [5]:
import seaborn as sns
sns.set()

In [6]:
plt.rcParams["font.family"] = "STXIHEI"

In [7]:
import statsmodels.api as sm

In [8]:
from sklearn import datasets
boston = datasets.load_boston()

In [9]:
boston.data

array([[  6.32000000e-03,   1.80000000e+01,   2.31000000e+00, ...,
          1.53000000e+01,   3.96900000e+02,   4.98000000e+00],
       [  2.73100000e-02,   0.00000000e+00,   7.07000000e+00, ...,
          1.78000000e+01,   3.96900000e+02,   9.14000000e+00],
       [  2.72900000e-02,   0.00000000e+00,   7.07000000e+00, ...,
          1.78000000e+01,   3.92830000e+02,   4.03000000e+00],
       ..., 
       [  6.07600000e-02,   0.00000000e+00,   1.19300000e+01, ...,
          2.10000000e+01,   3.96900000e+02,   5.64000000e+00],
       [  1.09590000e-01,   0.00000000e+00,   1.19300000e+01, ...,
          2.10000000e+01,   3.93450000e+02,   6.48000000e+00],
       [  4.74100000e-02,   0.00000000e+00,   1.19300000e+01, ...,
          2.10000000e+01,   3.96900000e+02,   7.88000000e+00]])

In [12]:
boston.values

<function Bunch.values>

In [13]:
bostondf = pd.DataFrame(boston.data, columns = boston.feature_names)
bostondf.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [16]:
from sklearn import preprocessing
std = preprocessing.StandardScaler()
std

StandardScaler(copy=True, with_mean=True, with_std=True)

In [17]:
from sklearn import linear_model
reg = linear_model.LinearRegression()
reg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [18]:
std.get_params()

{'copy': True, 'with_mean': True, 'with_std': True}

In [19]:
std.fit(boston.data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [20]:
std.mean_

array([  3.59376071e+00,   1.13636364e+01,   1.11367787e+01,
         6.91699605e-02,   5.54695059e-01,   6.28463439e+00,
         6.85749012e+01,   3.79504269e+00,   9.54940711e+00,
         4.08237154e+02,   1.84555336e+01,   3.56674032e+02,
         1.26530632e+01])

In [21]:
std.var_

array([  7.37586143e+01,   5.42861840e+02,   4.69714297e+01,
         6.43854770e-02,   1.34010989e-02,   4.92695216e-01,
         7.90792473e+02,   4.42525226e+00,   7.56665313e+01,
         2.83486236e+04,   4.67772630e+00,   8.31828042e+03,
         5.08939794e+01])

In [23]:
ZX = std.transform(boston.data)
ZX[:2]

array([[-0.41771335,  0.28482986, -1.2879095 , -0.27259857, -0.14421743,
         0.41367189, -0.12001342,  0.1402136 , -0.98284286, -0.66660821,
        -1.45900038,  0.44105193, -1.0755623 ],
       [-0.41526932, -0.48772236, -0.59338101, -0.27259857, -0.74026221,
         0.19427445,  0.36716642,  0.55715988, -0.8678825 , -0.98732948,
        -0.30309415,  0.44105193, -0.49243937]])